{{- if .Values.applications.loadbalancer.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loadbalancer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
    path: applications/loadbalancer
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.applications.loadbalancer.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}