apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-values
data:
  values.yaml:  < /dev/null | 
    gitlab:
      global:
        hosts:
          domain: gitlab.example.com
        
        gitaly:
          persistence:
            size: 50Gi
        
        postgresql:
          persistence:
            size: 20Gi
        
        redis:
          persistence:
            size: 8Gi
      
      gitlab-runner:
        runners:
          config: |
            [[runners]]
              [runners.kubernetes]
              namespace = "gitlab-prod"
              image = "alpine:latest"
