apiVersion: v1
kind: ConfigMap
metadata:
  name: librechat-values
data:
  values.yaml:  < /dev/null | 
    librechat:
      ingress:
        hosts:
          - host: librechat.example.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: librechat-tls
            hosts:
              - librechat.example.com
      
      mongodb:
        persistence:
          size: 20Gi
      
      meilisearch:
        persistence:
          size: 10Gi
      
      resources:
        limits:
          cpu: 4
          memory: 4Gi
        requests:
          cpu: 2
          memory: 2Gi
