librechat:
  ingress:
    hosts:
      - host: librechat-staging.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: librechat-staging-tls
        hosts:
          - librechat-staging.example.com
  
  mongodb:
    persistence:
      size: 8Gi
  
  meilisearch:
    persistence:
      size: 4Gi
  
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
