influxdb2:
  persistence:
    size: 20Gi
  
  ingress:
    hostname: influxdb.example.com
    tls:
      - secretName: influxdb-tls
        hosts:
          - influxdb.example.com
  
  resources:
    limits:
      cpu: 4
      memory: 4Gi
    requests:
      cpu: 2
      memory: 2Gi
