loadbalancer:
  name: stackready-lb
  namespace: default
  
  service:
    type: LoadBalancer
    annotations:
    
    ports:
      - name: http
        port: 80
        targetPort: 80
        protocol: TCP
      - name: https
        port: 443
        targetPort: 443
        protocol: TCP
    
    selector:
      app: nginx-ingress
      component: controller
  
  externalTrafficPolicy: Cluster
  sessionAffinity: None
