apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-values
data:
  values.yaml: |
    influxdb2:
      persistence:
        size: 4Gi
      
      ingress:
        hostname: influxdb-dev.example.com
        tls:
          - secretName: influxdb-dev-tls
            hosts:
              - influxdb-dev.example.com
      
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 512Mi