apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeflow-values
data:
  values.yaml: |
    kubeflow:
      domain: kubeflow-dev.example.com
      
      notebook:
        defaultResources:
          cpu: "0.5"
          memory: "1Gi"
      
      pipeline:
        persistence:
          size: 10Gi