apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev
namePrefix: dev-

bases:
  - ../../base

commonLabels:
  environment: dev
  
patchesStrategicMerge:
  - nifi-values.yaml
  - gitlab-values.yaml
  - kubeflow-values.yaml
  - influxdb-values.yaml
  - librechat-values.yaml
  - loadbalancer-values.yaml